2021-06-06  :42:22 - ERROR - test_func.py - 80 - An error has been caught in function 'save_img', process 'MainProcess' (13548), thread 'MainThread' (4593804736):
Traceback (most recent call last):

  File "/Users/antx/Code/prm/BcAppAPI/test_func.py", line 100, in <module>
    img_save = save_img()
               └ <function save_img at 0x106010790>

> File "/Users/antx/Code/prm/BcAppAPI/test_func.py", line 80, in save_img
    mongodb.save_img(result)
    │       │        └ 'iVBORw0KGgoAAAANSUhEUgAAAdYAAAHWAQAAAADiYZX3AAADUElEQVR4nO2dQW7bMBBF/5QCuqSAHsBHkW/QIxW5mXSU3IBaGpAwXXCGpOwmUgK3dYz/F0Zk8YE2...
    │       └ <function MongoDB.save_img at 0x1050d2160>
    └ <utils.services.db.mongodb.MongoDB object at 0x103adfaf0>

  File "/Users/antx/Code/prm/BcAppAPI/utils/services/db/mongodb.py", line 144, in save_img
    save_data = self.collection.save(dict(img=bson.binary.Binary(img_content.getvalue())))
                │    │          │             │    │      │      └ 'iVBORw0KGgoAAAANSUhEUgAAAdYAAAHWAQAAAADiYZX3AAADUElEQVR4nO2dQW7bMBBF/5QCuqSAHsBHkW/QIxW5mXSU3IBaGpAwXXCGpOwmUgK3dYz/F0Zk8YE2...
                │    │          │             │    │      └ <class 'bson.binary.Binary'>
                │    │          │             │    └ <module 'bson.binary' from '/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/bson/binary.py'>
                │    │          │             └ <module 'bson' from '/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/bson/__init__.py'>
                │    │          └ <function Collection.save at 0x104b160d0>
                │    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'test'), 'test')
                └ <utils.services.db.mongodb.MongoDB object at 0x103adfaf0>

AttributeError: 'str' object has no attribute 'getvalue'
2021-06-06  :44:45 - ERROR - test_func.py - 88 - An error has been caught in function 'restore_img', process 'MainProcess' (13578), thread 'MainThread' (4553270720):
Traceback (most recent call last):

  File "/Users/antx/Code/prm/BcAppAPI/test_func.py", line 103, in <module>
    restore_img()
    └ <function restore_img at 0x10e655820>

> File "/Users/antx/Code/prm/BcAppAPI/test_func.py", line 88, in restore_img
    af_img = mongodb.read_img('60bbb7a930cfe1ea8ea3a1f8')
             │       └ <function MongoDB.read_img at 0x10d7174c0>
             └ <utils.services.db.mongodb.MongoDB object at 0x10c155fa0>

  File "/Users/antx/Code/prm/BcAppAPI/utils/services/db/mongodb.py", line 163, in read_img
    return_data = data[0]['img']
                  └ []

IndexError: list index out of range
2021-06-06  :45:37 - ERROR - test_func.py - 89 - An error has been caught in function 'restore_img', process 'MainProcess' (13590), thread 'MainThread' (4540863936):
Traceback (most recent call last):

  File "/Users/antx/Code/prm/BcAppAPI/test_func.py", line 104, in <module>
    restore_img()
    └ <function restore_img at 0x10cff1820>

> File "/Users/antx/Code/prm/BcAppAPI/test_func.py", line 89, in restore_img
    af_img = mongodb.read_img(ObjectId('60bbb7a930cfe1ea8ea3a1f8'))
             │       │        └ <class 'bson.objectid.ObjectId'>
             │       └ <function MongoDB.read_img at 0x10c0b44c0>
             └ <utils.services.db.mongodb.MongoDB object at 0x10aaf2fa0>

  File "/Users/antx/Code/prm/BcAppAPI/utils/services/db/mongodb.py", line 164, in read_img
    image = Image.open(StringIO(return_data))
            │     │    │        └ b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01\xd6\x00\x00\x01\xd6\x01\x00\x00\x00\x00\xe2a\x95\xf7\x00\x00\x03PIDATx\x9c\...
            │     │    └ <class '_io.StringIO'>
            │     └ <function open at 0x10c0a8280>
            └ <module 'PIL.Image' from '/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/PIL/Image.py'>

TypeError: initial_value must be str or None, not bytes
2021-06-06  :51:23 - ERROR - user_info.py - 59 - An error has been caught in function 'setup_profile', process 'SpawnProcess-192' (14318), thread 'MainThread' (4639163840):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x106eab430>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x106d38280>
           └ <SpawnProcess name='SpawnProcess-192' parent=7708 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x106d358b0>
    └ <SpawnProcess name='SpawnProcess-192' parent=7708 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x106f320a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-192' parent=7708 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-192' parent=7708 started>
    │    └ <function subprocess_started at 0x106ececa0>
    └ <SpawnProcess name='SpawnProcess-192' parent=7708 started>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x106f32040>>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x106ecde50>
    │    │                  └ <uvicorn.server.Server object at 0x106f32040>
    │    └ <function BaseEventLoop.run_until_complete at 0x1074b8700>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1074b8670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1074bb1f0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x107411550>
    └ <Handle <TaskWakeupMethWrapper object at 0x1097ed310>(<Future finis...6988381601792>)>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x1097ed310>(<Future finis...6988381601792>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x1097ed310>(<Future finis...6988381601792>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x1097ed310>(<Future finis...6988381601792>)>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x107913700>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x107913790>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x1078afbe0>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x1097af790>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x1078afbe0>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1097b51c0>
          └ <fastapi.applications.FastAPI object at 0x1097af790>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x1097b7ee0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x1097b5190>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1097b51c0>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x1097b7ee0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x1097b5100>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x1097b5190>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1097b7f70>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x1097afca0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x1097b5100>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1097b7f70>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x10866bdc0>
          └ <fastapi.routing.APIRoute object at 0x1097bffd0>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x1097b7f70>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1097d78e0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x1097b79d0>
          └ <fastapi.routing.APIRoute object at 0x1097bffd0>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x1097d7490>
                     └ <function get_request_handler.<locals>.app at 0x1097b7940>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x108657d30>
  File "/Users/antx/Code/prm/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_profile': SetupProfile(avatar=None, nickname='asd', sex='male', area='china', intro='这个家伙很懒，什么都没留下'), 'request': <star...
                 │         └ <function setup_profile at 0x1097a45e0>
                 └ <fastapi.dependencies.models.Dependant object at 0x1097c4100>

> File "./app/api/user_info.py", line 59, in setup_profile
    user_info_db.update_one(save_info)
    │            │          └ {'user_id': 3470266988381601792, 'base_info': {'profile': {'nickname': 'asd', 'sex': 'male', 'area': 'china', 'intro': '这个家伙很...
    │            └ <function MongoDB.update_one at 0x109254700>
    └ <utils.services.db.mongodb.MongoDB object at 0x109793c70>

TypeError: update_one() missing 1 required positional argument: 'new_data_dict'
