2021-06-10  :31:37 - ERROR - test_func.py - 120 - An error has been caught in function 'set_default_avatar', process 'MainProcess' (33017), thread 'MainThread' (4522849728):
Traceback (most recent call last):

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/test_func.py", line 124, in <module>
    set_default_avatar()
    └ <function set_default_avatar at 0x102a4f8b0>

> File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/test_func.py", line 120, in set_default_avatar
    mongodb.save_img(user_id='default', img=png_content)
    │       │                               └ b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\xf3\x00\x00\x01\n\x08\x06\x00\x00\x00\xc7\x1ccZ\x00\x00\x18OiCCPICC Profile...
    │       └ <function MongoDB.save_img at 0x10176e040>
    └ <utils.services.db.mongodb.MongoDB object at 0x10054bfa0>

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/utils/services/db/mongodb.py", line 146, in save_img
    save_data = base64.b64encode(bson.binary.Binary(img.getvalue())).decode('ascii')
                │      │         │    │      │      └ b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\xf3\x00\x00\x01\n\x08\x06\x00\x00\x00\xc7\x1ccZ\x00\x00\x18OiCCPICC Profile...
                │      │         │    │      └ <class 'bson.binary.Binary'>
                │      │         │    └ <module 'bson.binary' from '/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/bson/binary.py'>
                │      │         └ <module 'bson' from '/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/bson/__init__.py'>
                │      └ <function b64encode at 0x100859940>
                └ <module 'base64' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/base64.py'>

AttributeError: 'bytes' object has no attribute 'getvalue'
2021-06-10  :33:26 - ERROR - test_func.py - 120 - An error has been caught in function 'set_default_avatar', process 'MainProcess' (33058), thread 'MainThread' (4514846144):
Traceback (most recent call last):

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/test_func.py", line 124, in <module>
    set_default_avatar()
    └ <function set_default_avatar at 0x1035f08b0>

> File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/test_func.py", line 120, in set_default_avatar
    mongodb.save_img(user_id='default', img=png_content)
    │       │                               └ b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\xf3\x00\x00\x01\n\x08\x06\x00\x00\x00\xc7\x1ccZ\x00\x00\x18OiCCPICC Profile...
    │       └ <function MongoDB.save_img at 0x102326040>
    └ <utils.services.db.mongodb.MongoDB object at 0x1010ebfa0>

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/utils/services/db/mongodb.py", line 141, in save_img
    save_data = base64.b64encode(bson.binary.Binary(img.getvalue())).decode('ascii')
                │      │         │    │      │      └ b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\xf3\x00\x00\x01\n\x08\x06\x00\x00\x00\xc7\x1ccZ\x00\x00\x18OiCCPICC Profile...
                │      │         │    │      └ <class 'bson.binary.Binary'>
                │      │         │    └ <module 'bson.binary' from '/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/bson/binary.py'>
                │      │         └ <module 'bson' from '/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/bson/__init__.py'>
                │      └ <function b64encode at 0x1013f8940>
                └ <module 'base64' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/base64.py'>

AttributeError: 'bytes' object has no attribute 'getvalue'
2021-06-10  :52:22 - ERROR - exchange.py - 40 - An error has been caught in function 'get_miners', process 'SpawnProcess-33' (33502), thread 'MainThread' (4696327616):
Traceback (most recent call last):

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/encoders.py", line 134, in jsonable_encoder
    data = dict(obj)
                └ ObjectId('60c1ef6b83ec46e6a8db5da7')

TypeError: 'ObjectId' object is not iterable


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/encoders.py", line 138, in jsonable_encoder
    data = vars(obj)
                └ ObjectId('60c1ef6b83ec46e6a8db5da7')

TypeError: vars() argument must have __dict__ attribute


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x10b45a4c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x10b2e2310>
           └ <SpawnProcess name='SpawnProcess-33' parent=32047 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x10b2e0940>
    └ <SpawnProcess name='SpawnProcess-33' parent=32047 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x10b4dc0a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-33' parent=32047 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-33' parent=32047 started>
    │    └ <function subprocess_started at 0x10b47adc0>
    └ <SpawnProcess name='SpawnProcess-33' parent=32047 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x10b4dc040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x10b47a280>
    │    │                  └ <uvicorn.server.Server object at 0x10b4dc040>
    │    └ <function BaseEventLoop.run_until_complete at 0x10ba64670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10ba645e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10ba68160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10b9bd4c0>
    └ <Handle <TaskWakeupMethWrapper object at 0x10dabf250>(<Future finis...4271785435136>)>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x10dabf250>(<Future finis...4271785435136>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x10dabf250>(<Future finis...4271785435136>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x10dabf250>(<Future finis...4271785435136>)>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10bebf430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10bebf4c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10be5abe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x10da29fa0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10be5abe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10da30940>
          └ <fastapi.applications.FastAPI object at 0x10da29fa0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10da40f70>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x10da309d0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10da30940>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10da40f70>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x10da30a00>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x10da309d0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10dab4040>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x10da304f0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x10da30a00>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10dab4040>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x10cc1c5e0>
          └ <fastapi.routing.APIRoute object at 0x10da96760>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10dab4040>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10daaa760>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x10da40ca0>
          └ <fastapi.routing.APIRoute object at 0x10da96760>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x10daaa430>
                     └ <function get_request_handler.<locals>.app at 0x10da40c10>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10cc07670>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function get_miners at 0x10da238b0>
                 └ <fastapi.dependencies.models.Dependant object at 0x10da96850>

> File "./app/api/exchange.py", line 40, in get_miners
    return msg(status='success', data=miners)
           │                          └ [{'_id': ObjectId('60c1ef6b83ec46e6a8db5da7'), 'miner_name': 'MinerSnow', 'miner_month_reward': 1000, 'miner_power': '4THS', ...
           └ <function msg at 0x10d48e550>

  File "./utils/services/base/base_func.py", line 30, in msg
    return JSONResponse(content=jsonable_encoder(final_data))
           │                    │                └ {'message': [{'_id': ObjectId('60c1ef6b83ec46e6a8db5da7'), 'miner_name': 'MinerSnow', 'miner_month_reward': 1000, 'miner_powe...
           │                    └ <function jsonable_encoder at 0x10cc07310>
           └ <class 'starlette.responses.JSONResponse'>

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    └ <function jsonable_encoder at 0x10cc07310>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
    └ <function jsonable_encoder at 0x10cc07310>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    └ <function jsonable_encoder at 0x10cc07310>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
                     └ [TypeError("'ObjectId' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

ValueError: [TypeError("'ObjectId' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
